fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: ReaccionEstudio\ReaccionCMSBundle\Entity\User
    from_email:
        address:        info@albertolabs.com
        sender_name:    Admin
    service:
        mailer: reaccion_cms.user_mailer